import type { DailyPiece } from "./types";

export const DAILY_DECK_SIZE = 8;

/** Full mock catalog — personalized deck picks 8 per day from this pool */
export const PIECE_CATALOG: DailyPiece[] = [
  {
    id: "1",
    brand: "Our Legacy",
    name: "Boxy linen shirt",
    price: 245,
    size: "M",
    category: "tops",
    aestheticTags: ["minimal", "scandinavian"],
    priceRange: 2,
    color: "#e8e4dc",
  },
  {
    id: "2",
    brand: "Acne Studios",
    name: "Wide-leg denim",
    price: 320,
    size: "32",
    category: "bottoms",
    aestheticTags: ["denim", "minimal"],
    priceRange: 3,
    color: "#c9d4ce",
  },
  {
    id: "3",
    brand: "Lemaire",
    name: "Twisted jersey tee",
    price: 195,
    size: "S",
    category: "tops",
    aestheticTags: ["minimal", "parisian"],
    priceRange: 2,
    color: "#ddd5cc",
  },
  {
    id: "4",
    brand: "Martine Rose",
    name: "Track jacket",
    price: 410,
    size: "L",
    category: "outerwear",
    aestheticTags: ["streetwear", "sportswear"],
    priceRange: 3,
    color: "#d4c4bc",
  },
  {
    id: "5",
    brand: "Stüssy",
    name: "Vintage wash hoodie",
    price: 128,
    size: "XL",
    category: "tops",
    aestheticTags: ["streetwear", "vintage"],
    priceRange: 1,
    color: "#c5c9d0",
  },
  {
    id: "6",
    brand: "Kapital",
    name: "Bandana chore coat",
    price: 520,
    size: "2",
    category: "outerwear",
    aestheticTags: ["japanese", "workwear", "vintage"],
    priceRange: 4,
    color: "#e2d6d0",
  },
  {
    id: "7",
    brand: "A.P.C.",
    name: "Petit standard jeans",
    price: 210,
    size: "30",
    category: "bottoms",
    aestheticTags: ["denim", "minimal", "parisian"],
    priceRange: 2,
    color: "#bcc8c4",
  },
  {
    id: "8",
    brand: "The Row",
    name: "Cashmere crewneck",
    price: 890,
    size: "M",
    category: "tops",
    aestheticTags: ["luxury", "minimal"],
    priceRange: 4,
    color: "#ebe6e1",
  },
  {
    id: "9",
    brand: "Carhartt WIP",
    name: "Detroit jacket",
    price: 198,
    size: "L",
    category: "outerwear",
    aestheticTags: ["workwear", "streetwear"],
    priceRange: 2,
    color: "#d8d4c8",
  },
  {
    id: "10",
    brand: "Needles",
    name: "Rebuild flannel",
    price: 285,
    size: "M",
    category: "tops",
    aestheticTags: ["japanese", "vintage"],
    priceRange: 2,
    color: "#c4b8a8",
  },
  {
    id: "11",
    brand: "Visvim",
    name: "FBT sneakers",
    price: 680,
    size: "10",
    category: "footwear",
    aestheticTags: ["japanese", "heritage"],
    priceRange: 4,
    color: "#e0dcd4",
  },
  {
    id: "12",
    brand: "Palace",
    name: "Tri-ferg hoodie",
    price: 168,
    size: "L",
    category: "tops",
    aestheticTags: ["streetwear", "skate"],
    priceRange: 2,
    color: "#b8bcc4",
  },
  {
    id: "13",
    brand: "Issey Miyake",
    name: "Pleats trousers",
    price: 395,
    size: "2",
    category: "bottoms",
    aestheticTags: ["japanese", "avant-garde"],
    priceRange: 3,
    color: "#d0ccc4",
  },
  {
    id: "14",
    brand: "Levi's Vintage",
    name: "501 rigid denim",
    price: 145,
    size: "31",
    category: "bottoms",
    aestheticTags: ["denim", "vintage", "americana"],
    priceRange: 1,
    color: "#a8b4b0",
  },
  {
    id: "15",
    brand: "Rick Owens",
    name: "Geobasket highs",
    price: 920,
    size: "42",
    category: "footwear",
    aestheticTags: ["avant-garde", "luxury"],
    priceRange: 4,
    color: "#2a2a2a",
  },
  {
    id: "16",
    brand: "Brain Dead",
    name: "Graphic mesh tee",
    price: 95,
    size: "M",
    category: "tops",
    aestheticTags: ["streetwear", "graphic"],
    priceRange: 1,
    color: "#d4ccc0",
  },
  {
    id: "17",
    brand: "Nigel Cabourn",
    name: "Army deck jacket",
    price: 445,
    size: "48",
    category: "outerwear",
    aestheticTags: ["workwear", "heritage", "vintage"],
    priceRange: 3,
    color: "#8a9488",
  },
  {
    id: "18",
    brand: "Comme des Garçons",
    name: "Deconstructed blazer",
    price: 780,
    size: "M",
    category: "outerwear",
    aestheticTags: ["avant-garde", "japanese"],
    priceRange: 4,
    color: "#1a1a1a",
  },
  {
    id: "19",
    brand: "Noah",
    name: "Corduroy bucket hat",
    price: 68,
    size: "OS",
    category: "accessories",
    aestheticTags: ["streetwear", "prep"],
    priceRange: 1,
    color: "#6b5848",
  },
  {
    id: "20",
    brand: "Orslow",
    name: "Fatigue pants",
    price: 235,
    size: "32",
    category: "bottoms",
    aestheticTags: ["japanese", "workwear", "denim"],
    priceRange: 2,
    color: "#5c6458",
  },
  {
    id: "21",
    brand: "Balenciaga",
    name: "Oversized windbreaker",
    price: 1100,
    size: "M",
    category: "outerwear",
    aestheticTags: ["luxury", "streetwear"],
    priceRange: 4,
    color: "#3d4a5c",
  },
  {
    id: "22",
    brand: "Uniqlo U",
    name: "Merino turtleneck",
    price: 49,
    size: "L",
    category: "tops",
    aestheticTags: ["minimal", "basics"],
    priceRange: 1,
    color: "#2c2c2c",
  },
  {
    id: "23",
    brand: "Engineered Garments",
    name: "Fatigue shirt",
    price: 268,
    size: "M",
    category: "tops",
    aestheticTags: ["workwear", "americana"],
    priceRange: 2,
    color: "#4a5044",
  },
  {
    id: "24",
    brand: "Supreme",
    name: "Box logo crew",
    price: 198,
    size: "L",
    category: "tops",
    aestheticTags: ["streetwear", "skate", "hype"],
    priceRange: 2,
    color: "#c41e3a",
  },
];
