import type { NearbyStore } from "./types";

export const NYC_STORES: NearbyStore[] = [
  {
    id: "au-hazard",
    name: "Au Hazard",
    type: "Vintage Denim",
    distanceMiles: 0.4,
    rating: 4.8,
    reviewCount: 214,
    isOpen: true,
    priceRange: 2,
    color: "#ddd5cc",
    tags: ["vintage", "denim"],
  },
  {
    id: "blue-in-green",
    name: "Blue in Green",
    type: "Japanese Selvedge",
    distanceMiles: 0.7,
    rating: 4.9,
    reviewCount: 412,
    isOpen: true,
    priceRange: 4,
    color: "#c5c9d0",
    tags: ["japanese", "denim"],
  },
  {
    id: "tokio-7",
    name: "Tokio 7",
    type: "Japanese Vintage",
    distanceMiles: 0.9,
    rating: 4.7,
    reviewCount: 328,
    isOpen: false,
    priceRange: 3,
    color: "#e2d6d0",
    tags: ["japanese", "vintage"],
  },
  {
    id: "front-street",
    name: "Front Street General Store",
    type: "Vintage & Streetwear",
    distanceMiles: 1.1,
    rating: 4.6,
    reviewCount: 189,
    isOpen: true,
    priceRange: 2,
    color: "#bcc8c4",
    tags: ["vintage", "workwear"],
  },
  {
    id: "procell",
    name: "Procell",
    type: "Vintage Streetwear",
    distanceMiles: 1.3,
    rating: 4.5,
    reviewCount: 156,
    isOpen: true,
    priceRange: 3,
    color: "#e8e4dc",
    tags: ["vintage"],
  },
  {
    id: "what-goes-around",
    name: "What Goes Around Comes Around",
    type: "Designer Consignment",
    distanceMiles: 1.5,
    rating: 4.4,
    reviewCount: 521,
    isOpen: true,
    priceRange: 4,
    color: "#d4c4bc",
    tags: ["consignment", "vintage"],
  },
  {
    id: "pilgrim",
    name: "Pilgrim Surf + Supply",
    type: "Workwear & Surf",
    distanceMiles: 1.8,
    rating: 4.7,
    reviewCount: 267,
    isOpen: false,
    priceRange: 3,
    color: "#c9d4ce",
    tags: ["workwear"],
  },
  {
    id: "bandit",
    name: "Bandit",
    type: "Vintage Denim & Tees",
    distanceMiles: 2.1,
    rating: 4.6,
    reviewCount: 143,
    isOpen: true,
    priceRange: 2,
    color: "#ebe6e1",
    tags: ["vintage", "denim"],
  },
];
