import type { NearbyStore } from "./types";

/** NYC vintage & streetwear stores with real coordinates */
export const NYC_STORES: NearbyStore[] = [
  {
    id: "blue-in-green",
    name: "Blue in Green",
    type: "Japanese Selvedge",
    latitude: 40.7223,
    longitude: -73.9985,
    distanceMiles: 0,
    rating: 4.9,
    reviewCount: 412,
    isOpen: true,
    priceRange: 4,
    color: "#c5c9d0",
    tags: ["japanese", "denim"],
  },
  {
    id: "tokio-7",
    name: "Tokio 7",
    type: "Japanese Vintage",
    latitude: 40.7264,
    longitude: -73.9818,
    distanceMiles: 0,
    rating: 4.7,
    reviewCount: 328,
    isOpen: false,
    priceRange: 3,
    color: "#e2d6d0",
    tags: ["japanese", "vintage"],
  },
  {
    id: "front-general-store",
    name: "Front General Store",
    type: "Vintage & Streetwear",
    latitude: 40.7195,
    longitude: -73.9987,
    distanceMiles: 0,
    rating: 4.6,
    reviewCount: 189,
    isOpen: true,
    priceRange: 2,
    color: "#bcc8c4",
    tags: ["vintage", "workwear"],
  },
  {
    id: "what-goes-around",
    name: "What Goes Around Comes Around",
    type: "Designer Consignment",
    latitude: 40.723,
    longitude: -74.003,
    distanceMiles: 0,
    rating: 4.4,
    reviewCount: 521,
    isOpen: true,
    priceRange: 4,
    color: "#d4c4bc",
    tags: ["consignment", "vintage"],
  },
  {
    id: "screaming-mimis",
    name: "Screaming Mimi's",
    type: "Vintage & Retro",
    latitude: 40.7264,
    longitude: -73.9934,
    distanceMiles: 0,
    rating: 4.5,
    reviewCount: 198,
    isOpen: true,
    priceRange: 2,
    color: "#ddd5cc",
    tags: ["vintage"],
  },
  {
    id: "artifact-nyc",
    name: "Artifact NYC",
    type: "Curated Vintage",
    latitude: 40.7195,
    longitude: -74.005,
    distanceMiles: 0,
    rating: 4.6,
    reviewCount: 167,
    isOpen: true,
    priceRange: 3,
    color: "#e8e4dc",
    tags: ["vintage", "streetwear"],
  },
  {
    id: "procell",
    name: "Procell",
    type: "Vintage Streetwear",
    latitude: 40.722,
    longitude: -73.989,
    distanceMiles: 0,
    rating: 4.5,
    reviewCount: 156,
    isOpen: true,
    priceRange: 3,
    color: "#c9d4ce",
    tags: ["vintage", "streetwear"],
  },
  {
    id: "l-train-vintage",
    name: "L Train Vintage",
    type: "Vintage Clothing",
    latitude: 40.714,
    longitude: -73.961,
    distanceMiles: 0,
    rating: 4.3,
    reviewCount: 284,
    isOpen: true,
    priceRange: 1,
    color: "#ebe6e1",
    tags: ["vintage", "denim"],
  },
];
